/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kruwell.program;





import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.Timer;


/**
 *
 * @author pelaj
 * 
 */

  

public class sewabuku extends javax.swing.JFrame {
    
 
    
//    method untuk mengososngkan form pada input judl buku
    private void kosongkan_form(){
        textJudulbuku.setText(null);
    }
//    harga sewa
    private void harga_sewa(){
        String sewa="5000"; 
        biayaa.setText(sewa);
    }
// denda
   
    
   
//    menampilkan data ke table
    
    private void show_data(){
        
//        membuat model data dulu

        DefaultTableModel model =new DefaultTableModel();
        model.addColumn("NO.");
        model.addColumn("ID.");
        model.addColumn("Judul Buku.");
        model.addColumn("Tanggal Pinjam.");
        model.addColumn("Tanggal Harus Kembali.");
        model.addColumn("Tanggal Kembali.");
        model.addColumn("Denda.");
        model.addColumn("Biaya Sewa.");
        try{
            int no =1;
            String sql = "SELECT * FROM sewabuku";
            java.sql.Connection conn =(Connection)konfig.configDB();
            java.sql.Statement stm =conn.createStatement();
            java.sql.ResultSet res =stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
                
            }
            tabeldata.setModel(model);
            
        }catch (SQLException e){
            System.out.println("Error :" + e.getMessage());
        }
        
         }

    /**
     * Creates new form sewabuku
     */
    public sewabuku() {
        initComponents();
        harga_sewa(); 
        show_data(); // menampilkan data
        kosongkan_form(); // method mengkosongkan
        Tanggal(); // tanggal
        waktu(); // jam Atau waktu
        Tujuhari();
      
    }

// tanggal tuju hari    
public void Tujuhari(){
     Calendar cal = Calendar.getInstance();
     cal.add(Calendar.DATE, +7);
     SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
     String tgl =sdf.format(cal.getTime());
     
     tujuhari.setText(tgl);
        
    
}
        
//    untuk menampilkan tanggal
public void Tanggal(){
    Date w = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    String dd =sdf.format(w);
    l_tanggal.setText(dd);
}
//untuk menampilkan jam atau waktu 
Timer t;
SimpleDateFormat st;
public void waktu(){
    
   
    t = new Timer(0,new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e){
        Date dt = new Date();
        st =new SimpleDateFormat("hh:mm:ss:SSS a");
        String tt = st.format(dt);
        l_jam.setText(tt);
                
        
    }
});
    t.start();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        l_jam = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textJudulbuku = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        kembalikanbuku = new javax.swing.JButton();
        editdata = new javax.swing.JButton();
        delet = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        exit = new javax.swing.JButton();
        l_tanggal = new javax.swing.JLabel();
        biayaa = new javax.swing.JLabel();
        tujuhari = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Persewaan Buku");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Persewaan Buku");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tanggal :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Jam :");

        l_jam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel6.setText("Judul Buku :");

        textJudulbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textJudulbukuActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Biaya :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Rp");

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        kembalikanbuku.setText("Kembalikan Buku");
        kembalikanbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalikanbukuActionPerformed(evt);
            }
        });

        editdata.setText("Edit");
        editdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editdataActionPerformed(evt);
            }
        });

        delet.setText("Delete");
        delet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletActionPerformed(evt);
            }
        });

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NO", "Judul Buku", "Tanggal Pinjam", "Tanggal Harus Kembali", "Tanggal kembali", "Denda", "Biayay Sewa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabeldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabeldata);

        exit.setText("exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        l_tanggal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_tanggal.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                l_tanggalAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        biayaa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tujuhari.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("7 Hari Kedepan  :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(kembalikanbuku)
                                        .addGap(18, 18, 18)
                                        .addComponent(editdata)
                                        .addGap(18, 18, 18)
                                        .addComponent(delet)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(exit))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textJudulbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(l_tanggal)))
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(125, 125, 125)
                                                .addComponent(tujuhari, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(210, 210, 210)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(l_jam, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(biayaa, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tujuhari, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(l_jam, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l_tanggal))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textJudulbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(biayaa, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(kembalikanbuku)
                    .addComponent(editdata)
                    .addComponent(delet)
                    .addComponent(exit))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
//            String tanggal_kembali ="0";
            int denda =0;
            int sewa =0;
            String sql = "INSERT INTO sewabuku (judul_buku,tanggal_pinjam,tanggal_wajib_kembali,tanggal_kembali,denda,biaya_sewa) VALUES ('"+textJudulbuku.getText()+"','"+l_tanggal.getText()+"','"+tujuhari.getText()+"','"+l_tanggal.getText()+"','"+sewa+"','"+denda+"')";
            java.sql.Connection conn =(Connection)konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI SIMPAN");
            show_data();
            kosongkan_form();
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
                
                
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textJudulbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textJudulbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textJudulbukuActionPerformed

    private void l_tanggalAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_l_tanggalAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_l_tanggalAncestorAdded

    
//    hapus data
    private void deletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletActionPerformed
        // TODO add your handling code here:
        try{
            
            String sql ="DELETE FROM sewabuku WHERE judul_buku='"+textJudulbuku.getText()+"'";
            java.sql.Connection conn =(Connection)konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI HAPUS");
             
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        show_data();
        kosongkan_form(); 
    }//GEN-LAST:event_deletActionPerformed

    
//    untuk meng edit data
    private void editdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editdataActionPerformed
        // TODO add your handling code here:
        try{
            int row = tabeldata.getSelectedRow();
            String idupdate =tabeldata.getValueAt(row, 1).toString();
            
            String sql = "update sewabuku set judul_buku ='"+textJudulbuku.getText()+"' where id='"+idupdate+"' ";
            java.sql.Connection conn =(Connection)konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
           
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI EDIT");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
         show_data();
         kosongkan_form();
       
        
        
    }//GEN-LAST:event_editdataActionPerformed
// fungsi untuk seleksi table 
    private void tabeldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldataMouseClicked
        // TODO add your handling code here:
        int baris = tabeldata.rowAtPoint(evt.getPoint());
        String judul =tabeldata.getValueAt(baris, 2).toString();
        textJudulbuku.setText(judul);
        
        int bayar = tabeldata.rowAtPoint(evt.getPoint());
        String biaya =tabeldata.getValueAt(bayar, 7).toString();
        biayaa.setText(biaya);
        
    }//GEN-LAST:event_tabeldataMouseClicked

    private void kembalikanbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalikanbukuActionPerformed
        // TODO add your handling code here:
        try{
            int row = tabeldata.getSelectedRow();
            String idupdate =tabeldata.getValueAt(row, 1).toString();
            int denda =0;
            int sewa_buku=5000;
            String sql = "update sewabuku set tanggal_kembali ='"+l_tanggal.getText()+"',denda='"+denda+"',biaya_sewa='"+sewa_buku+"' where id='"+idupdate+"' ";
            java.sql.Connection conn =(Connection)konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
           
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI UPDATE /SUDAH MENGEMBALIKAN BUKU");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
         show_data();
         kosongkan_form();
       
        
        
    }//GEN-LAST:event_kembalikanbukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ParseException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sewabuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sewabuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sewabuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sewabuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        
        java.util.Date date=new java.util.Date();  
        System.out.println(date); 
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sewabuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel biayaa;
    private javax.swing.JButton delet;
    private javax.swing.JButton editdata;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kembalikanbuku;
    private javax.swing.JLabel l_jam;
    private javax.swing.JLabel l_tanggal;
    private javax.swing.JTable tabeldata;
    private javax.swing.JTextField textJudulbuku;
    private javax.swing.JLabel tujuhari;
    // End of variables declaration//GEN-END:variables
}
